<a href="https://colab.research.google.com/github/nepridumalnik/Jupyter-Notebooks/blob/master/pytorch/tutorials/PyTorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Тензоры

Тензоры это специализированные структуры данных, очень схожие с массивами и матрицами. В PyTorch используются тензоры для кодирования вводов и выводов моделей, а также их параметров.

Тензоры схожи с `ndarray` из NumPy за исключением того, что могут запускаться на GPU и прочих аппаратных ускорителях. На деле тензоры и массивы NumPy могут разделять общую память без необходимости копирования (см. раздел [Bridge with NumPy](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label)). Тензоры также оптимизированы для автоматического дифференцирования (подробнее разбирается в секции [автоматический градиент](https://pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html)). Если вы знакомы с `ndarray`, будете чувствовать себя с Tensor API как дома, если нет - следуйте инструкциям!

In [26]:
import torch
import numpy as np


## Инициализация тензора

Тензор может быть инициализирован разными способами. Посмотрите на первый пример:

__Напрямую из данных__

Тензор может быть создан напрямую из данных, тип данных определится автоматически.

In [27]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

data, x_data


([[1, 2], [3, 4]],
 tensor([[1, 2],
         [3, 4]]))

__Из массива NumPy__

Тензор может быть создан из массива NumPy (и наоборот - см. раздел [Bridge with NumPy](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label)).

In [28]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

np_array, x_np


(array([[1, 2],
        [3, 4]]),
 tensor([[1, 2],
         [3, 4]]))

__Из другого тензора__

Новый тензор сохранит свойства (размер. тип данных) оригинального тензора, если они не будут явно переопределены.

In [29]:
x_ones = torch.ones_like(x_data) # Сохраняет свойства оригинального тензора
print(f"Ones Tensor:\n{x_ones}")

x_rand = torch.rand_like(x_data, dtype=torch.float) # Тип данных оригинального тензора переопределён
print(f"Random Tensor:\n{x_rand}")


Ones Tensor:
tensor([[1, 1],
        [1, 1]])
Random Tensor:
tensor([[0.0425, 0.1797],
        [0.4216, 0.3326]])


__Со случайными или константными значениями__

`shape` это кортеж с измерениями тензора. В коде ниже он определяет размерность выходного тензора.

In [30]:
shape = (2, 3,)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor:\n{rand_tensor}")
print(f"Random Tensor:\n{ones_tensor}")
print(f"Random Tensor:\n{zeros_tensor}")


Random Tensor:
tensor([[0.0364, 0.6562, 0.7279],
        [0.0374, 0.3633, 0.2284]])
Random Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Random Tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Атрибуты тензора

Атрибуты тензоров описывают их размер, тип данных и устройство на котором они хранятся.

In [31]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Type of tensor: {tensor.dtype}")
print(f"Device of tensor: {tensor.device}")


Shape of tensor: torch.Size([3, 4])
Type of tensor: torch.float32
Device of tensor: cpu


## Операции с тензорами

Более сотни операция с тензорами, включая арифметические, линейную алгебру, работу с матрицами (транспонирование, индексация, срезы), сэмплирование и многое другое подробно описаны [здесь](https://pytorch.org/docs/stable/torch.html).

Каждая из этих операция может быть запущена на GPU (так как обычно это быстрее, чем на CPU). Если вы используете Colab, выделите GPU, пройдя в `Среда выполнения` -> `Сменить среду выполнения`.

По умолчанию тензоры создаются на CPU, необходимо явно переместить их на GPU, используя метод `.to` (после проверки, доступности GPU). Помните, что копирование больших тензоров между устройствами может быть дорогим по времени и памяти!

In [32]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

tensor.device


device(type='cuda', index=0)

Попробуйте операции из списка ниже. Если вы знакомы с NumPy API, вы найдёте, что Tensor API очень прост в использовании.

In [33]:
tensor = torch.ones(4, 4)

print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[:, -1]}")

tensor[:, 1] = 0
print(tensor)


First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


__Объединение тензоров__

Вы можете использовать `torch.cat` для конкатенации последовательности тензоров вдоль указанного измерения. Смотри также [torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html), другую операцию по объединению тензоров, которая немного отличается от `torch.cat`.

In [34]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t1


tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

__Арифметические операции__


In [35]:
# Это применит операцию матричного умножения между двумя тензорами.
# y1, y2 и y3 будут иметь одинаковые значения.
y1 = tensor @ tensor
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

print(f"y1: {y1}")
print(f"y2: {y2}")
print(f"y3: {y3}")

# Это применит поэлементное умножение.
# z1, z2 и z3 будут иметь одинаковые значения.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(f"z1: {y1}")
print(f"z2: {y2}")
print(f"z3: {y3}")


y1: tensor([[3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.]])
y2: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y3: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
z1: tensor([[3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.]])
z2: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
z3: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


__Одноэлементный тензор__

Если есть тензор размером в один элемент, например, после сложения всех значений в одно, можно конвертировать это в числовое значение Python, используя метод `item()`:

In [36]:
agg = tensor.sum()
agg_item = agg.item()
agg_item


12.0

__In-place операции (без дополнительного использования памяти)__

Операции, которые сохраняют результат в операнд, называются `in-place`. Они отмечены `_` суффиксом. Например: `x.copy_(y)`, `x.t_()`, изменят `x`.

In [37]:
print(f"Tensor: {tensor}")
tensor.add_(5)
print(f"Tensor: {tensor}")


Tensor: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
Tensor: tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


# Трансляция с NumPy
Тензоры на CPU и NumPy массивы могут разделять общую память и изменение одного приводит к изменению другого.

## Тензор в массив NumPy

In [38]:
t = torch.ones(5)
print(f"t: {t}")

n = t.numpy()
print(f"n: {n}")


t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [39]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")


t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


## NumPy массив в тензор

In [40]:
n = np.ones(5)
t = torch.from_numpy(n)

print(f"t: {t}")
print(f"n: {n}")


t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n: [1. 1. 1. 1. 1.]


In [41]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")


t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


In [42]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")


t: tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
n: [3. 3. 3. 3. 3.]
